### ISSUE TITLE
update to disgord v0.21+

### ISSUE THREAD

**Issue by andersfylling** [Salmonllama/gourd#14]
Hi, to properly handle the breaking change regarding intents (discord api v6 is now deprecated) I suggest upgrading to disgord v0.21.
I know there used to be a bug in v0.20 regarding the cache causing deadlocks, but this has been fixed now.

Nice project!

**Comment by andersfylling** [comment]
if you are interesting in keeping the project alive, I can help moving to the latest disgord version =)

**Comment by Salmonllama** [comment]
I would like to keep the project alive, yes. Life's just been busy with college, and work. On top of that, I have a Java version of this that is currently in production, so Gourd ends up getting neglected.

My goal with this was to swap my Discord bot over to Go, it just hasn't made it to the point where I can do that yet.

Is there documentation of breaking changes somewhere? I've been skimming discussions in Discord-Go server, but there was too much to follow :P

**Comment by andersfylling** [comment]
no worries, im about to give you a PR

**Comment by andersfylling** [comment]
This should get you going: https://github.com/Salmonllama/gourd/pull/15

Maybe I should PR it into a different branch for now?

**Comment by andersfylling** [comment]
new PR: https://github.com/Salmonllama/gourd/pull/16

**Comment by Salmonllama** [comment]
Merged, thank you very much!
